services:
  - type: web
    name: mindflex-backend
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && gunicorn --config gunicorn.conf.py wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: PORT
        value: 10000
    healthCheckPath: /api/health
    autoDeploy: true 